import { createClient } from '@supabase/supabase-js';import { describe,expect,it } from 'vitest';
import WebSocket from 'ws';
const transport=WebSocket as never;
const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;const anon=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;const run=url&&key&&anon?describe:describe.skip;
run('Supabase production schema',()=>{
  const admin=createClient(url!,key!,{auth:{persistSession:false},realtime:{transport}});
  it('exposes the migrated schema and RPCs',async()=>{const tables=['profiles','services','customers','quotes','quote_items','acceptances','payments','appointments','quote_events','documents','subscriptions','webhook_events','reminders'];for(const table of tables){const{error}=await admin.from(table).select('*',{head:true,count:'exact'});expect(error,table).toBeNull()}const{error}=await admin.rpc('consume_rate_limit',{p_key:`integration:${Date.now()}`,p_limit:1,p_window_seconds:60});expect(error).toBeNull()});
  it('executes quote, payment and appointment transactions through RLS',async()=>{const stamp=Date.now();const email=`integration-${stamp}@fechazap.invalid`;const password=`Fz!${stamp}xY`;const{data:created,error:createError}=await admin.auth.admin.createUser({email,password,email_confirm:true});expect(createError).toBeNull();const userId=created.user!.id;try{expect((await admin.from('profiles').insert({user_id:userId,slug:`test-${stamp}`,business_name:'Teste FechaZap'})).error).toBeNull();const authClient=createClient(url!,anon!,{auth:{persistSession:false},realtime:{transport}});const{data:session,error:signInError}=await authClient.auth.signInWithPassword({email,password});expect(signInError).toBeNull();const userDb=createClient(url!,anon!,{global:{headers:{Authorization:`Bearer ${session.session!.access_token}`}},auth:{persistSession:false},realtime:{transport}});const{data:customer,error:customerError}=await userDb.from('customers').insert({user_id:userId,name:'Cliente Teste',phone:`55${stamp}`}).select().single();expect(customerError).toBeNull();const{data:quote,error:quoteError}=await userDb.from('quotes').insert({user_id:userId,customer_id:customer.id,status:'draft'}).select().single();expect(quoteError).toBeNull();const{data:updated,error:updateError}=await userDb.rpc('replace_quote_items',{p_quote_id:quote.id,p_title:'Servico Teste',p_discount_cents:500,p_expires_at:null,p_items:[{serviceId:null,description:'Item',quantity:2,unitPriceCents:2500,sortOrder:0}]});expect(updateError).toBeNull();expect(updated.subtotal_cents).toBe(5000);expect(updated.total_cents).toBe(4500);for(const state of ['sent','accepted','contracted','awaiting_payment']){const{error}=await userDb.rpc('transition_quote',{quote_id:quote.id,next_status:state,transition_reason:'integration'});expect(error,state).toBeNull()}const{data:paid,error:paidError}=await userDb.rpc('confirm_manual_payment',{p_quote_id:quote.id});expect(paidError).toBeNull();expect(paid.status).toBe('paid');const startsAt=new Date(Date.now()+172800000).toISOString();const{data:slot,error:slotError}=await userDb.from('appointments').insert({quote_id:quote.id,starts_at:startsAt,status:'offered'}).select().single();expect(slotError).toBeNull();const{data:selected,error:selectedError}=await admin.rpc('select_appointment',{p_public_token:quote.public_token,p_appointment_id:slot.id});expect(selectedError).toBeNull();expect(selected.status).toBe('selected');const{data:final}=await admin.from('quotes').select('status').eq('id',quote.id).single();expect(final?.status).toBe('scheduled')}finally{await admin.auth.admin.deleteUser(userId)}});
});
